### ISSUE TITLE
רעיונות לפרוייקטים בבסיסי נתונים

### ISSUE THREAD

**Issue by yair-go** [Lev-Academic-Center/150225-5780-Databases#1]
בשרשור הזה יש להציע בתגובות ארגונים עבור הפרוייקטים לקבוצות השונות
כדאי לחשוב אם הארגון מספיק מורכב כך שמכיל מספר אגפים ובכל אגף יש מספר ישויות

כשרושמים ארגון כדאי לרשום גם מספר ישויות שיש בארגון.

 אפשר להיעזר בנספח בחוברת הקורס
[ובדוגמאות משנה שעברה ](https://docs.google.com/spreadsheets/d/1SBV__qIy19CjgzHl0xbQbU_2zbsVz5K2386GBDL8_F8/edit?usp=sharing) 
נדרש מייל של המכון כדי לצפות

**Comment by alonsh194** [comment]
יש לנו רעיון על קניות באינטרנט:
מוכר\ספק
קונים
אתר
מוצר
עגלת קניות

**Comment by yair-go** [comment]
תסתכלו בדוגמאות משנה שעברה, צריך לפתח את הנושא

**Comment by avihudamari** [comment]
אפשר לבחור מרכז חינוכי, יש המון אופציות ליישויות וזה נושא שקרוב אלינו..
כללי: תלמיד, מרצה, קורס, קמפוס, בניין, כיתה, כתובת.
שירותים במרכז החינוכי: ספריה, קפטריה, חדר כושר, מעונות.
מנהלה של מרכז החינוכי: כוח אדם, חשבונות תלמידים, אחזקה, תמיכה טכנית.

פחות או יותר..

**Comment by yair-go** [comment]
@avihudamari היה שנה שעברה

**Comment by hezi3188** [comment]
אפשר לעשות רשת שמנהלת רכבים ומוסכים וכו

**Comment by avihudamari** [comment]
אפשר בית חולים:
ישויות כלליות: מטופל, רופא, מנתח, אחות
מחלקות, בניינים, קומות, חדרים,
בדיקה, מחלה, תרופה,
 ,שירותים בבית החולים: אבטחה, ניקיון, מסעדות, חנויות, תחזוקה, כספים, אדמיניסטרציה
ועוד...
מקווה שזה לא היה בשנים עברו.......

**Comment by yair-go** [comment]
@avihudamari תסתכל ברעיון אצל קבוצה 42
זה כבר די מפותח שם

@hezi3188 רעיון טוב
להמשיך לפתח

**Comment by asafleve123** [comment]
**מציעים רפי ואסף-**



רשת חנויות בגדים:
סניפים
מחלקות בתוך כל סניף
מוכרים
לקוחות
בגדים
רכישות
ספקים
הזמנות
מחסנים
יצרנים
שליחים
אחמשים
מנהלים



תיאטרון:
אולמות 
שחקנים
תפאורה
מושבים
הצגות
הזמנות
בימאים
מזנון
כרטיסים
עיר
צלם
עובדים מאחורי הקלעים

אימוץ וקניית חיות:
חיות לאימוץ
חיות לקניה
מזון לחיות
עובדים
סניפים
עיר
דוח מכירה
דוח אימוץ
ציוד לחיות
לקוחות
ספקי ציוד
ספקי חיות
מרפאות

**Comment by ElishaMayer** [comment]
אפשר לעשות מערכת לבדיקת ומעקב אחרי חולי קורונה למשרד הבריאות
:רשימת ישויות
חולה
אזרח
מיקום
בדיקה
תוצאת בדיקה
בקשה להיבדק
עיר
שכונה
רופא
מרכז בדיקות
אשפוז
בית חולים
מלונית
דוח סטטיסטיקה שכונתית
דוח סטטיסטיקה עירונית

**Comment by yair-go** [comment]
@ElishaMayer  תצרף את זה 
[ברעיון לקבוצה 42](https://github.com/Lev-Academic-Center/150225-5780-Databases/issues/2)

**Comment by yair-go** [comment]
אני סוגר את הנושא הזה
תמשיכו להגיב בנושאים לפי קבוצות
